### ISSUE TITLE
error in paperclip copy method as it works only for windows 

### ISSUE THREAD

**Issue by RemasteredGod** [gegelendvay/Password-Generator#2]
![Screenshot 2023-11-02 224247](https://github.com/gegelendvay/Password-Generator/assets/97588514/ec008d8a-40fc-4717-9377-bbac82ac8f1d)

**Comment by gegelendvay** [comment]
Hey @AshstarTempest! Could you provide more information about the issue, like the system you are using? I recently tested the program on macOS 14, and it worked perfectly fine.
